root = "."

[build]
  cmd = "go build -o ./tmp/main ./cmd/api"
  bin = "./tmp/main"
  delay = 1000
  stop_on_error = true
  send_interrupt = true
  exclude_dir = ["tmp", "vendor", "node_modules", ".git"]

[log]
  time = true

[color]
  main = "cyan"
  watcher = "yellow"
  build = "green"
  runner = "magenta"

[screen]
  clear_on_rebuild = true
